### PR TITLE
Upgrade to React v16

### PR DESCRIPTION
**Pull request by sovanyio**
Including toggling the hydration skip in the `ComponentManager.initReactComponent` method

### CODE REVIEW

**Comment by stemey** [comment]
I fixed the master by pinning all dependencies. Tried to apply the changes to this PR but failed. Can you please update the PR, so that test succeed.

**Comment by sovanyio** [comment]
Done. I ran into some issues where `typeof React.Component` was being used with components that extended from that ancestor, which wouldn't pass the type checks--so those are now `any`. There is probably a more elegant solution to that problem, but I defer to you for that.

**Comment by stemey** [comment]
Thanks for all this great work. Please set the version to 0.5.0. Then I will merge it.

**Comment by sovanyio** [comment]
Updated

**Pull request merged**
